export const com_AE = [
         {
            id:"2025010300131-CICOM-SAJ",
            latitude: -13.020093,
            longitude: -39.609076,
            data: '2025-01-03' ,
            localizacao: "AMARGOSA, BA",
            bairro:"",
            aisp:"AISP 51-SANTO ANTONIO DE JESUS",
            lesionadoNaoAE: 1,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "GUARNIÇÃO INFORMOU QUE APÓS VÁRIAS DENÚNCIAS DA VÍTIMA, SR. PAULO DA SILVA, NA SEDE DA COMPANHIA, INFORMANDO QUE TERIA REGISTRADO UM B.O POR AMEAÇA, AGRESSÃO E EXPULSÃO DA SUA CASA PELO SEU PRÓPRIO FILHO, A GUARNIÇÃO SAIU EM DILIGÊNCIA COM O MESMO, A FIM DE VERIFICAR A SITUAÇÃO. CHEGANDO AO LOCAL, E EM PATRULHAMENTO RURAL FOI AVISTADO UM INDIVÍDUO EM FRENTE DA REFERIDA RESIDÊNCIA E, QUE AO PERCEBER A PRESENÇA DA POLÍCIA PASSOU A EFETUAR DISPAROS DE ARMA DE FOGO CONTRA A GU, MOMENTO EM QUE OS POLICIAIS REAJIRAM À INJUSTA AGRESSÃO. LOGO EM SEGUIDA, VISUALIZAMOS O INDIVÍDUO AO SOLO, EM POSSE DE UMA ARMA DE FOGO E FERIDO. DE IMEDIATO FOI PRESTADO SOCORRO LEVANDO-O PARA O HOSPITAL MUNICIPAL DE AMARGOSA, ONDE FOI ATESTADO O ÓBITO PELA EQUIPE MÉDICA DE PLANTÃO."
            
        },
        {
            id: "476021",
            latitude: -12.848922,
            longitude: -38.47080375,
            data: "2025-03-04",
            localizacao: "SALVADOR, BA",
            bairro: "FAZENDA COUTOS",
            aisp: "AISP 05-PERIPERI",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "GUARNIÇÃO PEDIU APOIO APÓS HOMENS ARMADOS EFETUAREM DISPAROS CONTRA OS POLICIAIS"
         },
        {
            id: "2025013100310-CICOM-BAR",
            latitude: -12.01136196558930,
            longitude: -44.71354494761550,
            data: "2025-01-31",
            localizacao: "ANGICAL, BA",
            bairro: "",
            aisp: "AISP 30-BARREIRAS",
            lesionadoNaoAE: 1,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "TROCA DE TIROS NA BA 447."
        },
        {
            id: "2025042100227-CICOM-JEQ",
            latitude: -14.3657885,
            longitude: -39.9381027,
            data: "2025-04-21",
            localizacao: "BOA NOVA, BA",
            bairro: "",
            aisp: "AISP 57-VITÓRIA DA CONQUISTA",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "SOLICITOU APOIO DAS VIATURAS POIS ENTROU EM CONFRONTO COM SUSPEITOS DE ROUBO DE UM HOTEL FAZENDA NA REGIÃO DE BOA NOVA. OP SGT PM NEVES"
        },
        {
            id: "452255",
            latitude: -12.9016076,
            longitude: -38.4386857,
            data: "2025-01-18",
            localizacao: "SALVADOR, BA",
            bairro: "CASTELO BRANCO",
            aisp: "AISP 10-PAU DA LIMA",
            lesionadoNaoAE: 1,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "COMANDANTE DA VIATURA 9.4720 INFORMOU QUE ESTEVE NO LOCAL PARAVERIFICAR AINFORMAÇÃO DESTA OCORRÊNCIA, AO REALIZAR RONDA, HOMENS ARMADOS EFETUARAM DISPAROS CONTRA OS POLICIAIS. HOUVE O REVIDE E APÓS O CONFRONTO, FOI ENCONTRADO UM RESISTENTE AO SOLO ALVEJADO. GUARNIÇÃO PRESTANDO SOCORRO AO INDIVÍDUO BALEADO AO HOSPITAL ELÁDIO LASSERE"
        },
        {
            id: "462378",
            latitude: -12.94281,
            longitude: -38.448405,
            data: "2025-02-07",
            localizacao: "SALVADOR, BA",
            bairro: "BEIRU/TANCREDO NEVES",
            aisp: "AISP 11-TANCREDO NEVES",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "O COMANDANTEDAGUARNIÇÃO INFORMOUTROCADE TIROS NALOCALIDADECOMAS VTR9.4870 EVTR9.2331. NÃO HÁVÍTIMAS BALEADAS."
        },
        {
            id: "462877",
            latitude: -12.6929295,
            longitude: -38.3380149,
            data: "2025-02-08",
            localizacao: "CAMACARI, BA",
            bairro: "",
            aisp: "AISP 22-CAMACARI",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "INFORMOUO CMTDAGUARNIÇÃO 8.1221 QUEALERTADO PORPOPULARES, HAVIAMALGUNS INDIVÍDUOS ARMADOS NESTALOCALIDADE. INCONTINENTE, DESLOCARAME FORAMRECEBIDOS COMDISPAROS DEARMADE FOGO. HOUVE O REVIDE EOS ACUSADOS CONSEGUIRAMEVADIRPORUMMATAGAL ENÃO FORAMLOCALIZADOS."
        },
        {
            id: "464142",
            latitude: -12.7001932,
            longitude: -38.325345,
            data: "2025-02-10",
            localizacao: "CAMACARI, BA",
            bairro: "",
            aisp: "AISP 22-CAMACARI",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "POR VOLTA DAS 14H15 , O POLICIAMENTO MOTOCICLISCO SOLICITOU APOIO PARA TROCA DE TIRO."
        },
        {
            id: "477865",
            latitude: -12.973689,
            longitude: -38.492226,
            data: "2025-03-08",
            localizacao: "SALVADOR, BA",
            bairro: "LUIZ ANSELMO",
            aisp: "AISP 06-BROTAS",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "COMANDANTE DA VTR INFORMOU TROCA DE TIROS COM HOMENS ARMADOS."
        },
        {
            id: "485240",
            latitude: -12.7001932,
            longitude: -38.325345,
            data: "2025-03-20",
            localizacao: "CAMACARI, BA",
            bairro: "",
            aisp: "AISP 22-CAMACARI",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "RONDESP RMS 02/03 INFORMOU CONFRONTO COM 6 ELEMENTOS QUE EVADIRAM-SE PARA ÁREA DE MATA."
        },
        {
            id: "489524",
            latitude: -12.95866616,
            longitude: -38.45243168,
            data: "2025-03-27",
            localizacao: "SALVADOR, BA",
            bairro: "CABULA",
            aisp: "AISP 11-TANCREDO NEVES",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "O COMANDANTE DA GUARNIÇÃO 9.2321 INFORMOU VIA RÁDIO QUE OCORREU UMA TENTATIVA DE ROUBO A UM TRANSEUNTE NAS PROXIMIDADES DO ACESSO DO HOSPITAL ROBERTO SANTOS. HOUVE REAÇÃO DA VÍTIMA E UM DOS HOMENS FOI DETIDO COM ARMA DE FOGO E UMA MOTO COM RESTRIÇÃO DE ROUBO"
        },
        {
            id: "489790",
            latitude: -12.8215994,
            longitude: -38.2335515,
            data: "2025-03-28",
            localizacao: "CAMACARI, BA",
            bairro: "",
            aisp: "AISP 22-CAMACARI",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "O CMT DA VTR 9.5912 INFORMOU QUE UM INDIVÍDUO EM ATITUDE SUSPEITA, AO AVISTAR A GUARNIÇÃO, EFETUOU DISPAROS DE ARMA DE FOGO CONTRA A VIATURA."
        },
        {
            id: "495508",
            latitude: -12.8957486,
            longitude: -38.4416258,
            data: "2025-04-06",
            localizacao: "SALVADOR, BA",
            bairro: "AGUAS CLARAS",
            aisp: "AISP 13-CAJAZEIRAS",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "O COMANDANTE DA 8.2217, INFORMOU, VIA RÁDIO, QUE HOUVE UM CONFRONTO COM A EQUIPE NA LOCALIDADE SUPRAMENCIONADA, CONTUDO, OS INDIVÍDUOS, APÓS A TROCA DE TIROS, CONSEGUIRAM FUGAR DA EQUIPE POLICIAL."
        },
        {
            id: "497616",
            latitude: -12.988191,
            longitude: -38.478795,
            data: "2025-04-10",
            localizacao: "SALVADOR, BA",
            bairro: "BROTAS",
            aisp: "AISP 06-BROTAS",
            lesionadoNaoAE: 2,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "O IPC MARCELO BATISTA, PLANTONISTA DO POSTO POLICIAL DO HGE, INFORMA QUE DEU ENTRADA NESTA UNIDADE HOSPITALAR, ÀS 17:01H DO DIA VIGENTE, SOCORRIDOS PELA PM, A PESSOA DE BRUNO BARRETO DE OLIVEIRA DO CARMO, 24 ANOS E ALISSON DE SOUZA CONCEIÇÃO, 16 ANOS. AMBOS ENVOLVIDOS NO CONFRONTO ARMADO COM AS GUARNIÇÕES PM. ESTADO DE SAÚDE NÃO INFORMADO. SERÃO APRESENTADOS NA DAI. BO: 273493/2025."
        },
            {
            id: "500568",
            latitude: -12.7001932,
            longitude: -38.325345,
            data: "2025-04-15",
            localizacao: "CAMACARI, BA",
            bairro: "",
            aisp: "AISP 22-CAMACARI",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "O COMANDANTE DA ORLA 21 INFORMOU QUE QUANDO EM RONDAS NO LOCAL SE DEPAROU COM ELEMENTOS EM UMA MOTOCICLETA E QUE AO AVISTAR A GUARNIÇÃO DISPAROU CONTRA OS POLICIAIS EVADIRAM DEIXANDO UMA MOCICLETA NO LOCAL."
        },
        {
            id: "504379",
            latitude: -12.6432816,
            longitude: -38.0844505,
            data: "2025-04-20",
            localizacao: "CAMACARI, BA",
            bairro: "",
            aisp: "AISP 22-CAMACARI",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "COMANDANTE DA GUARNIÇÃO 9.5920 INFORMOU VIA RADIO TROCA DE TIROS COM INDIVIDUOS ARMADOS NA LOCALIDADE. COMPONENTES DA GUARNIÇÃO ESTÃO BEM E NÃO HÁ REGISTRO DE OPONENTES BALEADOS."
        },
        {
            id: "450080",
            latitude: -12.6739188,
            longitude: -38.5335965,
            data: "2025-01-14",
            localizacao: "CANDEIAS, BA",
            bairro: "",
            aisp: "AISP 26-CANDEIAS",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "INFORMOU QUE INDIVIDUOS AO AVISTAR O MOTO PATRULHAMENTO EFETUOU DISPAROS DE ARMA DE FOGO. NÃO HOUVE VÍTIMAS"
        },
        {
            id: "450698",
            latitude: -12.950118,
            longitude: -38.439554,
            data: "2025-01-16",
            localizacao: "SALVADOR, BA",
            bairro: "ARENOSO",
            aisp: "AISP 11-TANCREDO NEVES",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "GUARNIÇÕES DE TANCREDO NEVES E RONDESP CENTRAL INFORMARAM TROCA DE TIRO"
        },
        {
            id: "476137",
            latitude: -12.6725892,
            longitude: -38.543179,
            data: "2025-03-05",
            localizacao: "CANDEIAS, BA",
            bairro: "",
            aisp: "AISP 26-CANDEIAS",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "SEGUNDO O COMANDANTE DA GUARNIÇÃO 9.1007 INFORMOU TROCA DE TIRO."
        },
        {
            id: "496945",
            latitude: -12.8566766,
            longitude: -38.4658154,
            data: "2025-04-08",
            localizacao: "SALVADOR, BA",
            bairro: "COUTOS",
            aisp: "AISP 05-PERIPERI",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "GUARNIÇÃO INFORMOU CONFRONTO ARMADO COM UM GRUPO DE INDIVIDUOS. SOLICITANDO APOIO"
        },
        {
            id: "2025041200692-CICOM-FSA",
            latitude: -12.331,
            longitude: -38.767,
            data: "2025-04-12",
            localizacao: "CONCEICAO DO JACUIPE, BA",
            bairro: "",
            aisp: "AISP 50-SANTO AMARO",
            lesionadoNaoAE: 1,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "Que a guarnição informou troca de tiros na localidade supra citada e estaria prestando socorro a um resistente. Diligencia em andamento. OP PM CSS 8173"
        },
        {
            id: "455124",
            latitude: -12.3892571,
            longitude: -37.8825897,
            data: "2025-01-24",
            localizacao: "ENTRE RIOS, BA",
            bairro: "",
            aisp: "AISP 48-RIO REAL",
            lesionadoNaoAE: 1,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "GUARNIÇÃO DO TOR, 6.0342, INFORMOU CONFRONTO ARMADO, NAS IMEDIAÇÕES DO PONTO DO MEL, E ESTÃO EM DESLOCAMENTO PARA PRESTAÇÃO DE SOCORRO AO RESISTENTE"
        },
        {
            id: "492753",
            latitude: -12.8910122,
            longitude: -38.43519,
            data: "2025-04-01",
            localizacao: "SALVADOR, BA",
            bairro: "CAJAZEIRAS",
            aisp: "AISP 13-CAJAZEIRAS",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "COMANDANTE DA GUARNIÇÃO 8.2205 INFORMOU TROCA DE TIRO NO LOCAL."
        },
        {
            id: "2025031700049-CICOM-PSG",
            latitude: null,
            longitude: null,
            data: "2025-03-17",
            localizacao: "EUNAPOLIS, BA",
            bairro: "",
            aisp: "AISP 35-EUNAPOLIS",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "COMPARECEU NA CENTRAL DE FLAGRANTES DA DT DE EUNÁPOLIS, UMA GU PM APRESENTANDO O NACIONAL TAYMON FLORENTINO AMORIM, [...] ENCONTRADO EM UMA BOLSA COR PRETA [...]"
        },
        {
            id: "2025031700067-CICOM-PSG",
            latitude: null,
            longitude: null,
            data: "2025-03-17",
            localizacao: "EUNAPOLIS, BA",
            bairro: "",
            aisp: "AISP 35-EUNAPOLIS",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "GUARNIÇÃO DA RONDESP INFORMOU TROCA DE TIRO COM FACÇÃO E SOLICITOU APOIO, QUE DE IMEDIATO FOI PASSADO ALERTA GERAL PARA 7ª CIPM EUNÁPOLIS."
        },
        {
            id: "2025041200017-CICOM-PSG",
            latitude: null,
            longitude: null,
            data: "2025-04-12",
            localizacao: "EUNAPOLIS, BA",
            bairro: "",
            aisp: "AISP 35-EUNAPOLIS",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "GUARNIÇÃO 9.0770 SOLICITOU INFORMADO QUE ENCONTRAVA-SE ENCURRALADA PRECISANDO DE APOIO TROCA DE TIROS."
        },
        {
            id: "499553",
            latitude: -12.9403131,
            longitude: -38.4843269,
            data: "2025-04-13",
            localizacao: "SALVADOR, BA",
            bairro: "ALTO DO PERU",
            aisp: "",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "GUARNIÇÃO DA VTR 9.0902, INFORMOU QUE FOI RECEBIDA A TIROS POR VÁRIOS INDIVÍDUOS ARMADOS"
        },
        {
            id: "2025042500164-CICOM-PSG",
            latitude: null,
            longitude: null,
            data: "2025-04-25",
            localizacao: "EUNAPOLIS, BA",
            bairro: "",
            aisp: "AISP 35-EUNAPOLIS",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "ESTE CICOM TOMOU CONHECIMENTO ATRAVÉS DO DPC ADRIANO, DE UMA TROCA DE TIROS ENVOLVENDO POLICIAIS CIVIS, ONDE FOI SOLICITADO APOIO DA PM."
        },
        {
            id: "2025010400289-CICOM-FSA",
            latitude: -12.2242804,
            longitude: -39.0081253,
            data: "2025-01-04",
            localizacao: "FEIRA DE SANTANA, BA",
            bairro: "2023 - NAO INFORMADO - 01ª COORPIN - FEIRA DE SANTANA",
            aisp: "AISP 36-FEIRA DE SANTANA",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "O comandante da guarnição da viatura 9.6623 informou que realizava rondas no bairro Campo do Gado Novo quando homens atiraram contra a guarnição. [...]"
        },
        {
            id: "447466",
            latitude: -12.8882965,
            longitude: -38.4262102,
            data: "2025-01-09",
            localizacao: "SALVADOR, BA",
            bairro: "CAJAZEIRAS",
            aisp: "AISP 13-CAJAZEIRAS",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "A GUARNIÇÃO DO CETO DO 22ºBPM, R-0073, INFORMOU QUE EM RONDAS PELO LOCAL FORAM RECEBIDOS A TIROS POR HOMENS ARMADOS E QUE EM SEGUIDA EVADIRAM PARA ZONA DE MATA NO LOCAL."
        },
        {
            id: "2025011200211-CICOM-FSA",
            latitude: null,
            longitude: null,
            data: "2025-01-12",
            localizacao: "FEIRA DE SANTANA, BA",
            bairro: "2023 - NAO INFORMADO - 01ª COORPIN - FEIRA DE SANTANA",
            aisp: "AISP 36-FEIRA DE SANTANA",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "Relata que houve vários disparos de arma de fogo nesse momento, pede apoio de uma viatura no local. Não soube informar se tem alguém alvejado, nem os autores dos disparos."
        },
        {
            id: "2025012100015-CICOM-FSA",
            latitude: -12.2828808,
            longitude: -38.9863243,
            data: "2025-01-21",
            localizacao: "FEIRA DE SANTANA, BA",
            bairro: "2023 - NAO INFORMADO - 01ª COORPIN - FEIRA DE SANTANA",
            aisp: "AISP 36-FEIRA DE SANTANA",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "A guarnição da Rondesp 31101 informou, via rádio, que estava em rondas quando visualizou indivíduos suspeitos que efetuaram disparos de arma de fogo contra os policiais. [...]"
        },
        {
            id: "2025021500892-CICOM-FSA",
            latitude: -12.2780638,
            longitude: -38.9776726,
            data: "2025-02-15",
            localizacao: "FEIRA DE SANTANA, BA",
            bairro: "NAN",
            aisp: "AISP 36-FEIRA DE SANTANA",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "Guarnição a bordo da viatura R 0027 informou via rádio que um homem a bordo de uma motocicleta de cor preta efetuou disparos de arma de fogo contra a viatura..."
        },
        {
            id: "2025022400576-CICOM-FSA",
            latitude: -12.2708673,
            longitude: -38.9816284,
            data: "2025-02-24",
            localizacao: "FEIRA DE SANTANA, BA",
            bairro: "NAN",
            aisp: "AISP 36-FEIRA DE SANTANA",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "Guarnição do motopatrulhamento do Garra solicitou apoio no rádio, informando que estava em troca de tiros com dois indivíduos armados..."
        },
        {
            id: "2025030200630-CICOM-FSA",
            latitude: null,
            longitude: null,
            data: "2025-03-02",
            localizacao: "FEIRA DE SANTANA, BA",
            bairro: "NAN",
            aisp: "AISP 36-FEIRA DE SANTANA",
            lesionadoNaoAE: 1,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "Guarnição policial a bordo da viatura 9.6623, informou confronto armado na citada localidade, e estaria prestando socorro à vítima..."
        },
        {
            id: "484173",
            latitude: -12.940442,
            longitude: -38.4515492,
            data: "2025-03-18",
            localizacao: "SALVADOR, BA",
            bairro: "BEIRU/TANCREDO NEVES",
            aisp: "AISP 11-TANCREDO NEVES",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "COMANDANTE DA VTR 9.2307 QUE INDIVÍDUOS INVADIRAM UMA RESIDÊNCIA E TENTARAM FAZER MORADOR DE REFÉM..."
        },
        {
            id: "497984",
            latitude: -12.942801,
            longitude: -38.46224925,
            data: "2025-04-11",
            localizacao: "SALVADOR, BA",
            bairro: "BARREIRAS",
            aisp: "AISP 11-TANCREDO NEVES",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "GUARNIÇÕES DO MOTO PATRULHAMENTO CENTRAL INFORMAM ALERTA GERAL POR TROCA DE TIROS NA LOCALIDADE"
        },
        {
            id: "2025042600762-CICOM-FSA",
            latitude: -12.2086201,
            longitude: -38.9732513,
            data: "2025-04-26",
            localizacao: "FEIRA DE SANTANA, BA",
            bairro: "",
            aisp: "AISP 36-FEIRA DE SANTANA",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "GUARNIÇÃO PM DA VTR R-0069 INFORMOU VIA RADIO QUE TENTOU ABORDAR DOIS HOMENS A BORDO DE UMA MOTOCICLETA..."
        },
        {
            id: "2025050300492-CICOM-FSA",
            latitude: -12.2079306,
            longitude: -38.9975929,
            data: "2025-05-03",
            localizacao: "FEIRA DE SANTANA, BA",
            bairro: "",
            aisp: "AISP 36-FEIRA DE SANTANA",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "O Tenente Kaick informou que em rondas pela referida localidade [...] houve disparos contra os policiais..."
        },
        {
            id: "499712",
            latitude: -12.8416514,
            longitude: -38.4575924,
            data: "2025-04-13",
            localizacao: "SALVADOR, BA",
            bairro: "ESTRADA DO DERBA",
            aisp: "",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "O COMANDANTE DA VIATURA 9.3103, HAVIA INFORMADO VIA RÁDIO, TROCA DE TIROS COM ALGUNS INDIVÍDUOS..."
        },
        {
            id: "2025042600247-CICOM-FSA",
            latitude: -12.0459547,
            longitude: -38.7659912,
            data: "2025-04-26",
            localizacao: "IRARA, BA",
            bairro: "",
            aisp: "AISP 29-ALAGOINHAS",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "GUARNIÇÃO DA VIATURA 99768 INFORMOU DISPAROS CONTRA A GUARNIÇÃO DURANTE RONDAS..."
        },
        {
            id: "2025040900041-CICOM-ITA",
            latitude: null,
            longitude: null,
            data: "2025-04-09",
            localizacao: "ITABUNA, BA",
            bairro: "NAN",
            aisp: "AISP 41-ITABUNA",
            lesionadoNaoAE: 1,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "INFORMA QUE EM RONDAS EM UMA OPERAÇÃO COM AS GUARNIÇÕES DA SOINT, RONDESP E CETO [...] UM DELES FOI BALEADO."
        },
        {
            id: "2025042200183-CICOM-ITB",
            latitude: null,
            longitude: null,
            data: "2025-04-22",
            localizacao: "ITAETÉ, BA",
            bairro: "",
            aisp: "AISP 42-ITABERABA",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "GUARNIÇÃO DA RONDESP CHAPADA INFORMOU QUE FOI RECEBIDA A TIROS POR 6 HOMENS ARMADOS [...]"
        },
        {
            id: "463406",
            latitude: -12.9413711,
            longitude: -38.4920023,
            data: "2025-02-09",
            localizacao: "SALVADOR, BA",
            bairro: "LIBERDADE",
            aisp: "AISP 02-LIBERDADE",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "COMANDANTE DA GÊMEOS 6.1009, INFORMOU TROCA DE TIROS COM ELEMENTOS ARMADOS."
        },
        {
            id: "2025042400596-CICOM-ITA",
            latitude: null,
            longitude: null,
            data: "2025-04-24",
            localizacao: "ITAJUIPE, BA",
            bairro: "",
            aisp: "AISP 41-ITABUNA",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "GUARNIÇÃO SOB O COMANDO DO CAP. PM BARBOSA FOI RECEBIDA COM DISPAROS PRÓXIMO À FAZENDA DELSAT."
        },
        {
            id: "458443",
            latitude: -12.9438308,
            longitude: -38.4496208,
            data: "2025-01-30",
            localizacao: "SALVADOR, BA",
            bairro: "BEIRU/TANCREDO NEVES",
            aisp: "AISP 11-TANCREDO NEVES",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "O COMANDANTE DA VIATURA 9.2321 INFORMOU QUE HOMENS ARMADOS EFETUARAM DISPAROS CONTRA A GUARNIÇÃO."
        },
        {
            id: "458440",
            latitude: -12.9495558,
            longitude: -38.495917,
            data: "2025-01-30",
            localizacao: "SALVADOR, BA",
            bairro: "LIBERDADE",
            aisp: "AISP 02-LIBERDADE",
            lesionadoNaoAE: 0,
            lesionadoAE: 0,
            obtidosAE: 0,
            descricao: "COMANDANTE DA GUARNIÇÃO 9.3725 INFORMOU QUE EM RONDAS NA CIDADE NOVA, A VIATURA FOI RECEBIDA A TIROS."
        },
  

 ];

export const SEM_AE = [
        
    ];

export const COM_OBITO = [
           
    ];

export const MUNICIPIOS_BAHIA = [
    
    ];